#%RAML 1.0
baseUri: https://anypoint.mulesoft.com/mocking/api/v1/links/d0c98701-f72d-4cf3-a6d2-ca39e32be633/ # 
version: 1.00
title: DummyProjectFromApiSpecification

traits:
  client-required:
    headers:
      client_id:
        type: string
      client_token:
        type: string

types:
  User: !include DataTypes/userDataType.raml
  Users: !include DataTypes/allUsersDataType.raml

/users:
  is: [client-required]
  get:
    queryParameters:
    responses:
      200:
        body:
          application/json:
            type: Users
            examples:
              !include Examples/AllUserExample.raml
              
  post:
    body: 
      application/json:
        type: User
        examples: 
           !include Examples/userexampleforpost.raml
    responses: 
      201:
        body: 
          application/json:
            example: 
              message: User added Successfully.......
  
  /{ID}:
    is: [client-required]
    get:
      responses: 
        200:
          body: 
            application/json:
              type: User
              examples:
                !include Examples/userexample.raml
    delete:
      responses:
        200:
          body:
            application/json:
              example:
                message: User deleted Successfully
    put:
      body:
        application/json:
          type: User
          examples: 
            !include Examples/userexample.raml
      responses:
        200:
          body:
            application/json:
              example:
                message: User Updated Successfully

